version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "wyre-technology/engineering"
    assignees:
      - "wyre-technology/engineering"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "wyre-technology/engineering"
    assignees:
      - "wyre-technology/engineering"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "wyre-technology/engineering"
    assignees:
      - "wyre-technology/engineering"
    commit-message:
      prefix: "ci"
      include: "scope"